### PR TITLE
added austrian "gemeinden" (communities)

### PR DESCRIPTION
**Pull request by FireFart**
This adds sites from austrian communities.

Source: http://www.staedtebund.gv.at/organisation/staedtebund/gvat-gemeindenamen.html

Parser for the site: https://gist.github.com/FireFart/bf8431125750e4ff0597

PS: "Steiermark" was not added because they link to a PDF which is not easy parseable

Also added the files generated by the script to `.gitignore`

### CODE REVIEW

**Comment by gutworth** [comment]
Thank you for the contribution. The Austria page already has quite a few more entries than other pages. My hope is a selection of representative and important sites can be listed that rather than every site there is.

**Comment by FireFart** [comment]
Hi @gutworth, thanks for your reply. So what do you think is your limit of listed sites per country? The generation of the content lasted a few minutes on my computer so I think it should be doable when splitting up the generation process. It surely depends on the rescan interval. I think every week or month would be a good start. If you split all sites over the whole week or month, it should also be not too much traffic.

**Comment by gutworth** [comment]
My concern is not the speed of the checker but the the length of the Austria page. My intention was not to create an exhaustive list of sites for every country but rather highlight important and popular websites. What are the 50-100 sites Austrians are most likely to be visiting?

**Comment by FireFart** [comment]
What do you think about adding the ALEXA top 50/100 on top and the other sites below (collapsed with jquery)? This could be doable for every country

**Comment by gutworth** [comment]
That's a possibility. We don't have the UI for it at the moment. My preference is a nicely curated small list.

**Pull request closed without merging**
